from collections import defaultdict

form = namedtuple('form', 'name type1 type2', defaults=(None,) * 3)
pkmn_form = defaultdict(lambda: None, {
    1: form(name="A"),
    2: form(name="B"),
    3: form(name="C"),
    4: form(name="D"),
    5: form(name="E"),
    6: form(name="F"),
    7: form(name="G"),
    8: form(name="H"),
    9: form(name="I"),
    10: form(name="J"),
    11: form(name="K"),
    12: form(name="L"),
    13: form(name="M"),
    14: form(name="N"),
    15: form(name="O"),
    16: form(name="P"),
    17: form(name="Q"),
    18: form(name="R"),
    19: form(name="S"),
    20: form(name="T"),
    21: form(name="U"),
    22: form(name="V"),
    23: form(name="W"),
    24: form(name="X"),
    25: form(name="Y"),
    26: form(name="Z"),
    27: form(name="!"),
    28: form(name="?"),
    29: form(name="Normal", type1="Normal"),
    30: form(name="Sunny", type1="Fire"),
    31: form(name="Rainy", type1="Water"),
    32: form(name="Snowy", type1="Ice"),
    33: form(name="Normal"),
    34: form(name="Attack"),
    35: form(name="Defense"),
    36: form(name="Speed"),
    37: form(name="0"),
    38: form(name="1"),
    39: form(name="2"),
    40: form(name="3"),
    41: form(name="4"),
    42: form(name="5"),
    43: form(name="6"),
    44: form(name="7"),
    45: None,
    46: form(name="Alolan", type1="Dark", type2="Normal"),
    47: None,
    48: form(name="Alolan", type1="Dark", type2="Normal"),
    49: None,
    50: form(name="Alolan", type1="Electric", type2="Psychic"),
    51: None,
    52: form(name="Alolan", type1="Ice", type2="Steel"),
    53: None,
    54: form(name="Alolan", type1="Ice", type2="Steel"),
    55: None,
    56: form(name="Alolan", type1="Ice"),
    57: None,
    58: form(name="Alolan", type1="Ice", type2="Fairy"),
    59: None,
    60: form(name="Alolan", type1="Ground", type2="Steel"),
    61: None,
    62: form(name="Alolan", type1="Ground", type2="Steel"),
    63: None,
    64: form(name="Alolan", type1="Dark"),
    65: None,
    66: form(name="Alolan", type1="Dark"),
    67: None,
    68: form(name="Alolan", type1="Rock", type2="Electric"),
    69: None,
    70: form(name="Alolan", type1="Rock", type2="Electric"),
    71: None,
    72: form(name="Alolan", type1="Rock", type2="Electric"),
    73: None,
    74: form(name="Alolan", type1="Poison", type2="Dark"),
    75: None,
    76: form(name="Alolan", type1="Poison", type2="Dark"),
    77: None,
    78: form(name="Alolan", type1="Grass", type2="Dragon"),
    79: None,
    80: form(name="Alolan", type1="Fire", type2="Ghost"),
    81: None,
    82: form(name="Frost", type1="Electric", type2="Ice"),
    83: form(name="Fan", type1="Electric", type2="Flying"),
    84: form(name="Mow", type1="Electric", type2="Grass"),
    85: form(name="Wash", type1="Electric", type2="Water"),
    86: form(name="Heat", type1="Electric", type2="Fire"),
    87: form(name="Plant Cloak", type1="Bug", type2="Grass"),
    88: form(name="Sandy Cloak", type1="Bug", type2="Ground"),
    89: form(name="Trash Cloak", type1="Bug", type2="Steel"),
    90: form(name="Altered Forme"),
    91: form(name="Origin Forme"),
    92: form(name="Sky Forme", type1="Grass", type2="Flying"),
    93: form(name="Land Forme", type2="Grass"),
    94: form(name="Overcast"),
    95: form(name="Sunshine"),
    96: form(name="West Sea"),
    97: form(name="East Sea"),
    98: form(name="West Sea"),
    99: form(name="East Sea"),
    100: None,
    101: form(name="Fighting", type1="Fighting"),
    102: form(name="Flying", type1="Flying"),
    103: form(name="Poison", type1="Poison"),
    104: form(name="Ground", type1="Ground"),
    105: form(name="Rock", type1="Rock"),
    106: form(name="Bug", type1="Bug"),
    107: form(name="Ghost", type1="Ghost"),
    108: form(name="Steel", type1="Steel"),
    109: form(name="Fire", type1="Fire"),
    110: form(name="Water", type1="Water"),
    111: form(name="Grass", type1="Grass"),
    112: form(name="Electric", type1="Electric"),
    113: form(name="Psychic", type1="Psychic"),
    114: form(name="Ice", type1="Ice"),
    115: form(name="Dragon", type1="Dragon"),
    116: form(name="Dark", type1="Dark"),
    117: form(name="Fairy", type1="Fairy"),
    118: form(name="Plant"),
    119: form(name="Sandy"),
    120: form(name="Trash")
    })
