from collections import defaultdict, namedtuple

pokemon = namedtuple('pokemon', 'name types')
pkmn_names = defaultdict(lambda: pokemon(name='MissingNo.', types={}), {
  1: pokemon(name='Bulbasaur', types={'Grass', 'Poison'}),
  2: pokemon(name='Ivysaur', types={'Grass', 'Poison'}),
  3: pokemon(name='Venusaur', types={'Grass', 'Poison'}),
  4: pokemon(name='Charmander', types={'Fire'}),
  5: pokemon(name='Charmeleon', types={'Fire'}),
  6: pokemon(name='Charizard', types={'Fire', 'Flying'}),
  7: pokemon(name='Squirtle', types={'Water'}),
  8: pokemon(name='Wartortle', types={'Water'}),
  9: pokemon(name='Blastoise', types={'Water'}),
  10: pokemon(name='Caterpie', types={'Bug'}),
  11: pokemon(name='Metapod', types={'Bug'}),
  12: pokemon(name='Butterfree', types={'Bug', 'Flying'}),
  13: pokemon(name='Weedle', types={'Bug', 'Poison'}),
  14: pokemon(name='Kakuna', types={'Bug', 'Poison'}),
  15: pokemon(name='Beedrill', types={'Bug', 'Poison'}),
  16: pokemon(name='Pidgey', types={'Normal', 'Flying'}),
  17: pokemon(name='Pidgeotto', types={'Normal', 'Flying'}),
  18: pokemon(name='Pidgeot', types={'Normal', 'Flying'}),
  19: pokemon(name='Rattata', types={'Normal'}),
  20: pokemon(name='Raticate', types={'Normal'}),
  21: pokemon(name='Spearow', types={'Normal', 'Flying'}),
  22: pokemon(name='Fearow', types={'Normal', 'Flying'}),
  23: pokemon(name='Ekans', types={'Poison'}),
  24: pokemon(name='Arbok', types={'Poison'}),
  25: pokemon(name='Pikachu', types={'Electric'}),
  26: pokemon(name='Raichu', types={'Electric'}),
  27: pokemon(name='Sandshrew', types={'Ground'}),
  28: pokemon(name='Sandslash', types={'Ground'}),
  29: pokemon(name='Nidoran♀', types={'Poison'}),
  30: pokemon(name='Nidorina', types={'Poison'}),
  31: pokemon(name='Nidoqueen', types={'Poison', 'Ground'}),
  32: pokemon(name='Nidoran♂', types={'Poison'}),
  33: pokemon(name='Nidorino', types={'Poison'}),
  34: pokemon(name='Nidoking', types={'Poison', 'Ground'}),
  35: pokemon(name='Clefairy', types={'Fairy'}),
  36: pokemon(name='Clefable', types={'Fairy'}),
  37: pokemon(name='Vulpix', types={'Fire'}),
  38: pokemon(name='Ninetales', types={'Fire'}),
  39: pokemon(name='Jigglypuff', types={'Normal', 'Fairy'}),
  40: pokemon(name='Wigglytuff', types={'Normal', 'Fairy'}),
  41: pokemon(name='Zubat', types={'Poison', 'Flying'}),
  42: pokemon(name='Golbat', types={'Poison', 'Flying'}),
  43: pokemon(name='Oddish', types={'Grass', 'Poison'}),
  44: pokemon(name='Gloom', types={'Grass', 'Poison'}),
  45: pokemon(name='Vileplume', types={'Grass', 'Poison'}),
  46: pokemon(name='Paras', types={'Bug', 'Grass'}),
  47: pokemon(name='Parasect', types={'Bug', 'Grass'}),
  48: pokemon(name='Venonat', types={'Bug', 'Poison'}),
  49: pokemon(name='Venomoth', types={'Bug', 'Poison'}),
  50: pokemon(name='Diglett', types={'Ground'}),
  51: pokemon(name='Dugtrio', types={'Ground'}),
  52: pokemon(name='Meowth', types={'Normal'}),
  53: pokemon(name='Persian', types={'Normal'}),
  54: pokemon(name='Psyduck', types={'Water'}),
  55: pokemon(name='Golduck', types={'Water'}),
  56: pokemon(name='Mankey', types={'Fighting'}),
  57: pokemon(name='Primeape', types={'Fighting'}),
  58: pokemon(name='Growlithe', types={'Fire'}),
  59: pokemon(name='Arcanine', types={'Fire'}),
  60: pokemon(name='Poliwag', types={'Water'}),
  61: pokemon(name='Poliwhirl', types={'Water'}),
  62: pokemon(name='Poliwrath', types={'Water', 'Fighting'}),
  63: pokemon(name='Abra', types={'Psychic'}),
  64: pokemon(name='Kadabra', types={'Psychic'}),
  65: pokemon(name='Alakazam', types={'Psychic'}),
  66: pokemon(name='Machop', types={'Fighting'}),
  67: pokemon(name='Machoke', types={'Fighting'}),
  68: pokemon(name='Machamp', types={'Fighting'}),
  69: pokemon(name='Bellsprout', types={'Grass', 'Poison'}),
  70: pokemon(name='Weepinbell', types={'Grass', 'Poison'}),
  71: pokemon(name='Victreebel', types={'Grass', 'Poison'}),
  72: pokemon(name='Tentacool', types={'Water', 'Poison'}),
  73: pokemon(name='Tentacruel', types={'Water', 'Poison'}),
  74: pokemon(name='Geodude', types={'Rock', 'Ground'}),
  75: pokemon(name='Graveler', types={'Rock', 'Ground'}),
  76: pokemon(name='Golem', types={'Rock', 'Ground'}),
  77: pokemon(name='Ponyta', types={'Fire'}),
  78: pokemon(name='Rapidash', types={'Fire'}),
  79: pokemon(name='Slowpoke', types={'Water', 'Psychic'}),
  80: pokemon(name='Slowbro', types={'Water', 'Psychic'}),
  81: pokemon(name='Magnemite', types={'Electric', 'Steel'}),
  82: pokemon(name='Magneton', types={'Electric', 'Steel'}),
  83: pokemon(name='Farfetch\'d', types={'Normal', 'Flying'}),
  84: pokemon(name='Doduo', types={'Normal', 'Flying'}),
  85: pokemon(name='Dodrio', types={'Normal', 'Flying'}),
  86: pokemon(name='Seel', types={'Water'}),
  87: pokemon(name='Dewgong', types={'Water', 'Ice'}),
  88: pokemon(name='Grimer', types={'Poison'}),
  89: pokemon(name='Muk', types={'Poison'}),
  90: pokemon(name='Shellder', types={'Water'}),
  91: pokemon(name='Cloyster', types={'Water', 'Ice'}),
  92: pokemon(name='Gastly', types={'Ghost', 'Poison'}),
  93: pokemon(name='Haunter', types={'Ghost', 'Poison'}),
  94: pokemon(name='Gengar', types={'Ghost', 'Poison'}),
  95: pokemon(name='Onix', types={'Rock', 'Ground'}),
  96: pokemon(name='Drowzee', types={'Psychic'}),
  97: pokemon(name='Hypno', types={'Psychic'}),
  98: pokemon(name='Krabby', types={'Water'}),
  99: pokemon(name='Kingler', types={'Water'}),
  100: pokemon(name='Voltorb', types={'Electric'}),
  101: pokemon(name='Electrode', types={'Electric'}),
  102: pokemon(name='Exeggcute', types={'Grass', 'Psychic'}),
  103: pokemon(name='Exeggutor', types={'Grass', 'Psychic'}),
  104: pokemon(name='Cubone', types={'Ground'}),
  105: pokemon(name='Marowak', types={'Ground'}),
  106: pokemon(name='Hitmonlee', types={'Fighting'}),
  107: pokemon(name='Hitmonchan', types={'Fighting'}),
  108: pokemon(name='Lickitung', types={'Normal'}),
  109: pokemon(name='Koffing', types={'Poison'}),
  110: pokemon(name='Weezing', types={'Poison'}),
  111: pokemon(name='Rhyhorn', types={'Ground', 'Rock'}),
  112: pokemon(name='Rhydon', types={'Ground', 'Rock'}),
  113: pokemon(name='Chansey', types={'Normal'}),
  114: pokemon(name='Tangela', types={'Grass'}),
  115: pokemon(name='Kangaskhan', types={'Normal'}),
  116: pokemon(name='Horsea', types={'Water'}),
  117: pokemon(name='Seadra', types={'Water'}),
  118: pokemon(name='Goldeen', types={'Water'}),
  119: pokemon(name='Seaking', types={'Water'}),
  120: pokemon(name='Staryu', types={'Water'}),
  121: pokemon(name='Starmie', types={'Water', 'Psychic'}),
  122: pokemon(name='Mr. Mime', types={'Psychic', 'Fairy'}),
  123: pokemon(name='Scyther', types={'Bug', 'Flying'}),
  124: pokemon(name='Jynx', types={'Ice', 'Psychic'}),
  125: pokemon(name='Electabuzz', types={'Electric'}),
  126: pokemon(name='Magmar', types={'Fire'}),
  127: pokemon(name='Pinsir', types={'Bug'}),
  128: pokemon(name='Tauros', types={'Normal'}),
  129: pokemon(name='Magikarp', types={'Water'}),
  130: pokemon(name='Gyarados', types={'Water', 'Flying'}),
  131: pokemon(name='Lapras', types={'Water', 'Ice'}),
  132: pokemon(name='Ditto', types={'Normal'}),
  133: pokemon(name='Eevee', types={'Normal'}),
  134: pokemon(name='Vaporeon', types={'Water'}),
  135: pokemon(name='Jolteon', types={'Electric'}),
  136: pokemon(name='Flareon', types={'Fire'}),
  137: pokemon(name='Porygon', types={'Normal'}),
  138: pokemon(name='Omanyte', types={'Rock', 'Water'}),
  139: pokemon(name='Omastar', types={'Rock', 'Water'}),
  140: pokemon(name='Kabuto', types={'Rock', 'Water'}),
  141: pokemon(name='Kabutops', types={'Rock', 'Water'}),
  142: pokemon(name='Aerodactyl', types={'Rock', 'Flying'}),
  143: pokemon(name='Snorlax', types={'Normal'}),
  144: pokemon(name='Articuno', types={'Ice', 'Flying'}),
  145: pokemon(name='Zapdos', types={'Electric', 'Flying'}),
  146: pokemon(name='Moltres', types={'Fire', 'Flying'}),
  147: pokemon(name='Dratini', types={'Dragon'}),
  148: pokemon(name='Dragonair', types={'Dragon'}),
  149: pokemon(name='Dragonite', types={'Dragon', 'Flying'}),
  150: pokemon(name='Mewtwo', types={'Psychic'}),
  151: pokemon(name='Mew', types={'Psychic'}),
  152: pokemon(name='Chikorita', types={'Grass'}),
  153: pokemon(name='Bayleef', types={'Grass'}),
  154: pokemon(name='Meganium', types={'Grass'}),
  155: pokemon(name='Cyndaquil', types={'Fire'}),
  156: pokemon(name='Quilava', types={'Fire'}),
  157: pokemon(name='Typhlosion', types={'Fire'}),
  158: pokemon(name='Totodile', types={'Water'}),
  159: pokemon(name='Croconaw', types={'Water'}),
  160: pokemon(name='Feraligatr', types={'Water'}),
  161: pokemon(name='Sentret', types={'Normal'}),
  162: pokemon(name='Furret', types={'Normal'}),
  163: pokemon(name='Hoothoot', types={'Normal', 'Flying'}),
  164: pokemon(name='Noctowl', types={'Normal', 'Flying'}),
  165: pokemon(name='Ledyba', types={'Bug', 'Flying'}),
  166: pokemon(name='Ledian', types={'Bug', 'Flying'}),
  167: pokemon(name='Spinarak', types={'Bug', 'Poison'}),
  168: pokemon(name='Ariados', types={'Bug', 'Poison'}),
  169: pokemon(name='Crobat', types={'Poison', 'Flying'}),
  170: pokemon(name='Chinchou', types={'Water', 'Electric'}),
  171: pokemon(name='Lanturn', types={'Water', 'Electric'}),
  172: pokemon(name='Pichu', types={'Electric'}),
  173: pokemon(name='Cleffa', types={'Fairy'}),
  174: pokemon(name='Igglybuff', types={'Normal', 'Fairy'}),
  175: pokemon(name='Togepi', types={'Fairy'}),
  176: pokemon(name='Togetic', types={'Fairy', 'Flying'}),
  177: pokemon(name='Natu', types={'Psychic', 'Flying'}),
  178: pokemon(name='Xatu', types={'Psychic', 'Flying'}),
  179: pokemon(name='Mareep', types={'Electric'}),
  180: pokemon(name='Flaaffy', types={'Electric'}),
  181: pokemon(name='Ampharos', types={'Electric'}),
  182: pokemon(name='Bellossom', types={'Grass'}),
  183: pokemon(name='Marill', types={'Water', 'Fairy'}),
  184: pokemon(name='Azumarill', types={'Water', 'Fairy'}),
  185: pokemon(name='Sudowoodo', types={'Rock'}),
  186: pokemon(name='Politoed', types={'Water'}),
  187: pokemon(name='Hoppip', types={'Grass', 'Flying'}),
  188: pokemon(name='Skiploom', types={'Grass', 'Flying'}),
  189: pokemon(name='Jumpluff', types={'Grass', 'Flying'}),
  190: pokemon(name='Aipom', types={'Normal'}),
  191: pokemon(name='Sunkern', types={'Grass'}),
  192: pokemon(name='Sunflora', types={'Grass'}),
  193: pokemon(name='Yanma', types={'Bug', 'Flying'}),
  194: pokemon(name='Wooper', types={'Water', 'Ground'}),
  195: pokemon(name='Quagsire', types={'Water', 'Ground'}),
  196: pokemon(name='Espeon', types={'Psychic'}),
  197: pokemon(name='Umbreon', types={'Dark'}),
  198: pokemon(name='Murkrow', types={'Dark', 'Flying'}),
  199: pokemon(name='Slowking', types={'Water', 'Psychic'}),
  200: pokemon(name='Misdreavus', types={'Ghost'}),
  201: pokemon(name='Unown', types={'Psychic'}),
  202: pokemon(name='Wobbuffet', types={'Psychic'}),
  203: pokemon(name='Girafarig', types={'Normal', 'Psychic'}),
  204: pokemon(name='Pineco', types={'Bug'}),
  205: pokemon(name='Forretress', types={'Bug', 'Steel'}),
  206: pokemon(name='Dunsparce', types={'Normal'}),
  207: pokemon(name='Gligar', types={'Ground', 'Flying'}),
  208: pokemon(name='Steelix', types={'Steel', 'Ground'}),
  209: pokemon(name='Snubbull', types={'Fairy'}),
  210: pokemon(name='Granbull', types={'Fairy'}),
  211: pokemon(name='Qwilfish', types={'Water', 'Poison'}),
  212: pokemon(name='Scizor', types={'Bug', 'Steel'}),
  213: pokemon(name='Shuckle', types={'Bug', 'Rock'}),
  214: pokemon(name='Heracross', types={'Bug', 'Fighting'}),
  215: pokemon(name='Sneasel', types={'Dark', 'Ice'}),
  216: pokemon(name='Teddiursa', types={'Normal'}),
  217: pokemon(name='Ursaring', types={'Normal'}),
  218: pokemon(name='Slugma', types={'Fire'}),
  219: pokemon(name='Magcargo', types={'Fire', 'Rock'}),
  220: pokemon(name='Swinub', types={'Ice', 'Ground'}),
  221: pokemon(name='Piloswine', types={'Ice', 'Ground'}),
  222: pokemon(name='Corsola', types={'Water', 'Rock'}),
  223: pokemon(name='Remoraid', types={'Water'}),
  224: pokemon(name='Octillery', types={'Water'}),
  225: pokemon(name='Delibird', types={'Ice', 'Flying'}),
  226: pokemon(name='Mantine', types={'Water', 'Flying'}),
  227: pokemon(name='Skarmory', types={'Steel', 'Flying'}),
  228: pokemon(name='Houndour', types={'Dark', 'Fire'}),
  229: pokemon(name='Houndoom', types={'Dark', 'Fire'}),
  230: pokemon(name='Kingdra', types={'Water', 'Dragon'}),
  231: pokemon(name='Phanpy', types={'Ground'}),
  232: pokemon(name='Donphan', types={'Ground'}),
  233: pokemon(name='Porygon2', types={'Normal'}),
  234: pokemon(name='Stantler', types={'Normal'}),
  235: pokemon(name='Smeargle', types={'Normal'}),
  236: pokemon(name='Tyrogue', types={'Fighting'}),
  237: pokemon(name='Hitmontop', types={'Fighting'}),
  238: pokemon(name='Smoochum', types={'Ice', 'Psychic'}),
  239: pokemon(name='Elekid', types={'Electric'}),
  240: pokemon(name='Magby', types={'Fire'}),
  241: pokemon(name='Miltank', types={'Normal'}),
  242: pokemon(name='Blissey', types={'Normal'}),
  243: pokemon(name='Raikou', types={'Electric'}),
  244: pokemon(name='Entei', types={'Fire'}),
  245: pokemon(name='Suicune', types={'Water'}),
  246: pokemon(name='Larvitar', types={'Rock', 'Ground'}),
  247: pokemon(name='Pupitar', types={'Rock', 'Ground'}),
  248: pokemon(name='Tyranitar', types={'Rock', 'Dark'}),
  249: pokemon(name='Lugia', types={'Psychic', 'Flying'}),
  250: pokemon(name='Ho-oh', types={'Fire', 'Flying'}),
  251: pokemon(name='Celebi', types={'Psychic', 'Grass'}),
  252: pokemon(name='Treecko', types={'Grass'}),
  253: pokemon(name='Grovyle', types={'Grass'}),
  254: pokemon(name='Sceptile', types={'Grass'}),
  255: pokemon(name='Torchic', types={'Fire'}),
  256: pokemon(name='Combusken', types={'Fire', 'Fighting'}),
  257: pokemon(name='Blaziken', types={'Fire', 'Fighting'}),
  258: pokemon(name='Mudkip', types={'Water'}),
  259: pokemon(name='Marshtomp', types={'Water', 'Ground'}),
  260: pokemon(name='Swampert', types={'Water', 'Ground'}),
  261: pokemon(name='Poochyena', types={'Dark'}),
  262: pokemon(name='Mightyena', types={'Dark'}),
  263: pokemon(name='Zigzagoon', types={'Normal'}),
  264: pokemon(name='Linoone', types={'Normal'}),
  265: pokemon(name='Wurmple', types={'Bug'}),
  266: pokemon(name='Silcoon', types={'Bug'}),
  267: pokemon(name='Beautifly', types={'Bug', 'Flying'}),
  268: pokemon(name='Cascoon', types={'Bug'}),
  269: pokemon(name='Dustox', types={'Bug', 'Poison'}),
  270: pokemon(name='Lotad', types={'Water', 'Grass'}),
  271: pokemon(name='Lombre', types={'Water', 'Grass'}),
  272: pokemon(name='Ludicolo', types={'Water', 'Grass'}),
  273: pokemon(name='Seedot', types={'Grass'}),
  274: pokemon(name='Nuzleaf', types={'Grass', 'Dark'}),
  275: pokemon(name='Shiftry', types={'Grass', 'Dark'}),
  276: pokemon(name='Taillow', types={'Normal', 'Flying'}),
  277: pokemon(name='Swellow', types={'Normal', 'Flying'}),
  278: pokemon(name='Wingull', types={'Water', 'Flying'}),
  279: pokemon(name='Pelipper', types={'Water', 'Flying'}),
  280: pokemon(name='Ralts', types={'Psychic', 'Fairy'}),
  281: pokemon(name='Kirlia', types={'Psychic', 'Fairy'}),
  282: pokemon(name='Gardevoir', types={'Psychic', 'Fairy'}),
  283: pokemon(name='Surskit', types={'Bug', 'Water'}),
  284: pokemon(name='Masquerain', types={'Bug', 'Flying'}),
  285: pokemon(name='Shroomish', types={'Grass'}),
  286: pokemon(name='Breloom', types={'Grass', 'Fighting'}),
  287: pokemon(name='Slakoth', types={'Normal'}),
  288: pokemon(name='Vigoroth', types={'Normal'}),
  289: pokemon(name='Slaking', types={'Normal'}),
  290: pokemon(name='Nincada', types={'Bug', 'Ground'}),
  291: pokemon(name='Ninjask', types={'Bug', 'Flying'}),
  292: pokemon(name='Shedinja', types={'Bug', 'Ghost'}),
  293: pokemon(name='Whismur', types={'Normal'}),
  294: pokemon(name='Loudred', types={'Normal'}),
  295: pokemon(name='Exploud', types={'Normal'}),
  296: pokemon(name='Makuhita', types={'Fighting'}),
  297: pokemon(name='Hariyama', types={'Fighting'}),
  298: pokemon(name='Azurill', types={'Normal', 'Fairy'}),
  299: pokemon(name='Nosepass', types={'Rock'}),
  300: pokemon(name='Skitty', types={'Normal'}),
  301: pokemon(name='Delcatty', types={'Normal'}),
  302: pokemon(name='Sableye', types={'Dark', 'Ghost'}),
  303: pokemon(name='Mawile', types={'Steel', 'Fairy'}),
  304: pokemon(name='Aron', types={'Steel', 'Rock'}),
  305: pokemon(name='Lairon', types={'Steel', 'Rock'}),
  306: pokemon(name='Aggron', types={'Steel', 'Rock'}),
  307: pokemon(name='Meditite', types={'Fighting', 'Psychic'}),
  308: pokemon(name='Medicham', types={'Fighting', 'Psychic'}),
  309: pokemon(name='Electrike', types={'Electric'}),
  310: pokemon(name='Manectric', types={'Electric'}),
  311: pokemon(name='Plusle', types={'Electric'}),
  312: pokemon(name='Minun', types={'Electric'}),
  313: pokemon(name='Volbeat', types={'Bug'}),
  314: pokemon(name='Illumise', types={'Bug'}),
  315: pokemon(name='Roselia', types={'Grass', 'Poison'}),
  316: pokemon(name='Gulpin', types={'Poison'}),
  317: pokemon(name='Swalot', types={'Poison'}),
  318: pokemon(name='Carvanha', types={'Water', 'Dark'}),
  319: pokemon(name='Sharpedo', types={'Water', 'Dark'}),
  320: pokemon(name='Wailmer', types={'Water'}),
  321: pokemon(name='Wailord', types={'Water'}),
  322: pokemon(name='Numel', types={'Fire', 'Ground'}),
  323: pokemon(name='Camerupt', types={'Fire', 'Ground'}),
  324: pokemon(name='Torkoal', types={'Fire'}),
  325: pokemon(name='Spoink', types={'Psychic'}),
  326: pokemon(name='Grumpig', types={'Psychic'}),
  327: pokemon(name='Spinda', types={'Normal'}),
  328: pokemon(name='Trapinch', types={'Ground'}),
  329: pokemon(name='Vibrava', types={'Ground', 'Dragon'}),
  330: pokemon(name='Flygon', types={'Ground', 'Dragon'}),
  331: pokemon(name='Cacnea', types={'Grass'}),
  332: pokemon(name='Cacturne', types={'Grass', 'Dark'}),
  333: pokemon(name='Swablu', types={'Normal', 'Flying'}),
  334: pokemon(name='Altaria', types={'Dragon', 'Flying'}),
  335: pokemon(name='Zangoose', types={'Normal'}),
  336: pokemon(name='Seviper', types={'Poison'}),
  337: pokemon(name='Lunatone', types={'Rock', 'Psychic'}),
  338: pokemon(name='Solrock', types={'Rock', 'Psychic'}),
  339: pokemon(name='Barboach', types={'Water', 'Ground'}),
  340: pokemon(name='Whiscash', types={'Water', 'Ground'}),
  341: pokemon(name='Corphish', types={'Water'}),
  342: pokemon(name='Crawdaunt', types={'Water', 'Dark'}),
  343: pokemon(name='Baltoy', types={'Ground', 'Psychic'}),
  344: pokemon(name='Claydol', types={'Ground', 'Psychic'}),
  345: pokemon(name='Lileep', types={'Rock', 'Grass'}),
  346: pokemon(name='Cradily', types={'Rock', 'Grass'}),
  347: pokemon(name='Anorith', types={'Rock', 'Bug'}),
  348: pokemon(name='Armaldo', types={'Rock', 'Bug'}),
  349: pokemon(name='Feebas', types={'Water'}),
  350: pokemon(name='Milotic', types={'Water'}),
  351: pokemon(name='Castform', types={'Normal'}),
  352: pokemon(name='Kecleon', types={'Normal'}),
  353: pokemon(name='Shuppet', types={'Ghost'}),
  354: pokemon(name='Banette', types={'Ghost'}),
  355: pokemon(name='Duskull', types={'Ghost'}),
  356: pokemon(name='Dusclops', types={'Ghost'}),
  357: pokemon(name='Tropius', types={'Grass', 'Flying'}),
  358: pokemon(name='Chimecho', types={'Psychic'}),
  359: pokemon(name='Absol', types={'Dark'}),
  360: pokemon(name='Wynaut', types={'Psychic'}),
  361: pokemon(name='Snorunt', types={'Ice'}),
  362: pokemon(name='Glalie', types={'Ice'}),
  363: pokemon(name='Spheal', types={'Ice', 'Water'}),
  364: pokemon(name='Sealeo', types={'Ice', 'Water'}),
  365: pokemon(name='Walrein', types={'Ice', 'Water'}),
  366: pokemon(name='Clamperl', types={'Water'}),
  367: pokemon(name='Huntail', types={'Water'}),
  368: pokemon(name='Gorebyss', types={'Water'}),
  369: pokemon(name='Relicanth', types={'Water', 'Rock'}),
  370: pokemon(name='Luvdisc', types={'Water'}),
  371: pokemon(name='Bagon', types={'Dragon'}),
  372: pokemon(name='Shelgon', types={'Dragon'}),
  373: pokemon(name='Salamence', types={'Dragon', 'Flying'}),
  374: pokemon(name='Beldum', types={'Steel', 'Psychic'}),
  375: pokemon(name='Metang', types={'Steel', 'Psychic'}),
  376: pokemon(name='Metagross', types={'Steel', 'Psychic'}),
  377: pokemon(name='Regirock', types={'Rock'}),
  378: pokemon(name='Regice', types={'Ice'}),
  379: pokemon(name='Registeel', types={'Steel'}),
  380: pokemon(name='Latias', types={'Dragon', 'Psychic'}),
  381: pokemon(name='Latios', types={'Dragon', 'Psychic'}),
  382: pokemon(name='Kyogre', types={'Water'}),
  383: pokemon(name='Groudon', types={'Ground'}),
  384: pokemon(name='Rayquaza', types={'Dragon', 'Flying'}),
  385: pokemon(name='Jirachi', types={'Steel', 'Psychic'}),
  386: pokemon(name='Deoxys (N})', types={'Psychic'}),
  387: pokemon(name='Turtwig', types={'Grass'}),
  388: pokemon(name='Grotle', types={'Grass'}),
  389: pokemon(name='Torterra', types={'Grass', 'Ground'}),
  390: pokemon(name='Chimchar', types={'Fire'}),
  391: pokemon(name='Monferno', types={'Fire', 'Fighting'}),
  392: pokemon(name='Infernape', types={'Fire', 'Fighting'}),
  393: pokemon(name='Piplup', types={'Water'}),
  394: pokemon(name='Prinplup', types={'Water'}),
  395: pokemon(name='Empoleon', types={'Water', 'Steel'}),
  396: pokemon(name='Starly', types={'Normal', 'Flying'}),
  397: pokemon(name='Staravia', types={'Normal', 'Flying'}),
  398: pokemon(name='Staraptor', types={'Normal', 'Flying'}),
  399: pokemon(name='Bidoof', types={'Normal'}),
  400: pokemon(name='Bibarel', types={'Normal', 'Water'}),
  401: pokemon(name='Kricketot', types={'Bug'}),
  402: pokemon(name='Kricketune', types={'Bug'}),
  403: pokemon(name='Shinx', types={'Electric'}),
  404: pokemon(name='Luxio', types={'Electric'}),
  405: pokemon(name='Luxray', types={'Electric'}),
  406: pokemon(name='Budew', types={'Grass', 'Poison'}),
  407: pokemon(name='Roserade', types={'Grass', 'Poison'}),
  408: pokemon(name='Cranidos', types={'Rock'}),
  409: pokemon(name='Rampardos', types={'Rock'}),
  410: pokemon(name='Shieldon', types={'Rock', 'Steel'}),
  411: pokemon(name='Bastiodon', types={'Rock', 'Steel'}),
  412: pokemon(name='Burmy', types={'Bug'}),
  413: pokemon(name='Wormadam (P})', types={'Bug', 'Grass'}),
  414: pokemon(name='Mothim', types={'Bug', 'Flying'}),
  415: pokemon(name='Combee', types={'Bug', 'Flying'}),
  416: pokemon(name='Vespiquen', types={'Bug', 'Flying'}),
  417: pokemon(name='Pachirisu', types={'Electric'}),
  418: pokemon(name='Buizel', types={'Water'}),
  419: pokemon(name='Floatzel', types={'Water'}),
  420: pokemon(name='Cherubi', types={'Grass'}),
  421: pokemon(name='Cherrim', types={'Grass'}),
  422: pokemon(name='Shellos', types={'Water'}),
  423: pokemon(name='Gastrodon', types={'Water', 'Ground'}),
  424: pokemon(name='Ambipom', types={'Normal'}),
  425: pokemon(name='Drifloon', types={'Ghost', 'Flying'}),
  426: pokemon(name='Drifblim', types={'Ghost', 'Flying'}),
  427: pokemon(name='Buneary', types={'Normal'}),
  428: pokemon(name='Lopunny', types={'Normal'}),
  429: pokemon(name='Mismagius', types={'Ghost'}),
  430: pokemon(name='Honchkrow', types={'Dark', 'Flying'}),
  431: pokemon(name='Glameow', types={'Normal'}),
  432: pokemon(name='Purugly', types={'Normal'}),
  433: pokemon(name='Chingling', types={'Psychic'}),
  434: pokemon(name='Stunky', types={'Poison', 'Dark'}),
  435: pokemon(name='Skuntank', types={'Poison', 'Dark'}),
  436: pokemon(name='Bronzor', types={'Steel', 'Psychic'}),
  437: pokemon(name='Bronzong', types={'Steel', 'Psychic'}),
  438: pokemon(name='Bonsly', types={'Rock'}),
  439: pokemon(name='Mime Jr.', types={'Psychic', 'Fairy'}),
  440: pokemon(name='Happiny', types={'Normal'}),
  441: pokemon(name='Chatot', types={'Normal', 'Flying'}),
  442: pokemon(name='Spiritomb', types={'Ghost', 'Dark'}),
  443: pokemon(name='Gible', types={'Dragon', 'Ground'}),
  444: pokemon(name='Gabite', types={'Dragon', 'Ground'}),
  445: pokemon(name='Garchomp', types={'Dragon', 'Ground'}),
  446: pokemon(name='Munchlax', types={'Normal'}),
  447: pokemon(name='Riolu', types={'Fighting'}),
  448: pokemon(name='Lucario', types={'Fighting', 'Steel'}),
  449: pokemon(name='Hippopotas', types={'Ground'}),
  450: pokemon(name='Hippowdon', types={'Ground'}),
  451: pokemon(name='Skorupi', types={'Poison', 'Bug'}),
  452: pokemon(name='Drapion', types={'Poison', 'Dark'}),
  453: pokemon(name='Croagunk', types={'Poison', 'Fighting'}),
  454: pokemon(name='Toxicroak', types={'Poison', 'Fighting'}),
  455: pokemon(name='Carnivine', types={'Grass'}),
  456: pokemon(name='Finneon', types={'Water'}),
  457: pokemon(name='Lumineon', types={'Water'}),
  458: pokemon(name='Mantyke', types={'Water', 'Flying'}),
  459: pokemon(name='Snover', types={'Ice', 'Grass'}),
  460: pokemon(name='Abomasnow', types={'Ice', 'Grass'}),
  461: pokemon(name='Weavile', types={'Dark', 'Ice'}),
  462: pokemon(name='Magnezone', types={'Electric', 'Steel'}),
  463: pokemon(name='Lickilicky', types={'Normal'}),
  464: pokemon(name='Rhyperior', types={'Ground', 'Rock'}),
  465: pokemon(name='Tangrowth', types={'Grass'}),
  466: pokemon(name='Electivire', types={'Electric'}),
  467: pokemon(name='Magmortar', types={'Fire'}),
  468: pokemon(name='Togekiss', types={'Fairy', 'Flying'}),
  469: pokemon(name='Yanmega', types={'Bug', 'Flying'}),
  470: pokemon(name='Leafeon', types={'Grass'}),
  471: pokemon(name='Glaceon', types={'Ice'}),
  472: pokemon(name='Gliscor', types={'Ground', 'Flying'}),
  473: pokemon(name='Mamoswine', types={'Ice', 'Ground'}),
  474: pokemon(name='Porygon-Z', types={'Normal'}),
  475: pokemon(name='Gallade', types={'Psychic', 'Fighting'}),
  476: pokemon(name='Probopass', types={'Rock', 'Steel'}),
  477: pokemon(name='Dusknoir', types={'Ghost'}),
  478: pokemon(name='Froslass', types={'Ice', 'Ghost'}),
  479: pokemon(name='Rotom', types={'Electric', 'Ghost'}),
  480: pokemon(name='Uxie', types={'Psychic'}),
  481: pokemon(name='Mesprit', types={'Psychic'}),
  482: pokemon(name='Azelf', types={'Psychic'}),
  483: pokemon(name='Dialga', types={'Steel', 'Dragon'}),
  484: pokemon(name='Palkia', types={'Water', 'Dragon'}),
  485: pokemon(name='Heatran', types={'Fire', 'Steel'}),
  486: pokemon(name='Regigigas', types={'Normal'}),
  487: pokemon(name='Giratina', types={'Ghost', 'Dragon'}),
  488: pokemon(name='Cresselia', types={'Psychic'}),
  489: pokemon(name='Phione', types={'Water'}),
  490: pokemon(name='Manaphy', types={'Water'}),
  491: pokemon(name='Darkrai', types={'Dark'}),
  492: pokemon(name='Shaymin', types={'Grass'}),
  493: pokemon(name='Arceus', types={'Normal'}),
  808: pokemon(name='Meltan', types={'Steel'}),
  809: pokemon(name='Melmetal', types={'Steel'})
})
