from collections import defaultdict, namedtuple

pokemon = namedtuple('pokemon', 'name type1 type2', defaults=(None,) * 3)
pkmn_names = defaultdict(lambda: pokemon(name='MissingNo.'), {
    1: pokemon(name='Bulbasaur', type1='Grass', type2='Poison'),
    2: pokemon(name='Ivysaur', type1='Grass', type2='Poison'),
    3: pokemon(name='Venusaur', type1='Grass', type2='Poison'),
    4: pokemon(name='Charmander', type1='Fire'),
    5: pokemon(name='Charmeleon', type1='Fire'),
    6: pokemon(name='Charizard', type1='Fire', type2='Flying'),
    7: pokemon(name='Squirtle', type1='Water'),
    8: pokemon(name='Wartortle', type1='Water'),
    9: pokemon(name='Blastoise', type1='Water'),
    10: pokemon(name='Caterpie', type1='Bug'),
    11: pokemon(name='Metapod', type1='Bug'),
    12: pokemon(name='Butterfree', type1='Bug', type2='Flying'),
    13: pokemon(name='Weedle', type1='Bug', type2='Poison'),
    14: pokemon(name='Kakuna', type1='Bug', type2='Poison'),
    15: pokemon(name='Beedrill', type1='Bug', type2='Poison'),
    16: pokemon(name='Pidgey', type1='Normal', type2='Flying'),
    17: pokemon(name='Pidgeotto', type1='Normal', type2='Flying'),
    18: pokemon(name='Pidgeot', type1='Normal', type2='Flying'),
    19: pokemon(name='Rattata', type1='Normal'),
    20: pokemon(name='Raticate', type1='Normal'),
    21: pokemon(name='Spearow', type1='Normal', type2='Flying'),
    22: pokemon(name='Fearow', type1='Normal', type2='Flying'),
    23: pokemon(name='Ekans', type1='Poison'),
    24: pokemon(name='Arbok', type1='Poison'),
    25: pokemon(name='Pikachu', type1='Electric'),
    26: pokemon(name='Raichu', type1='Electric'),
    27: pokemon(name='Sandshrew', type1='Ground'),
    28: pokemon(name='Sandslash', type1='Ground'),
    29: pokemon(name='Nidoran♀', type1='Poison'),
    30: pokemon(name='Nidorina', type1='Poison'),
    31: pokemon(name='Nidoqueen', type1='Poison', type2='Ground'),
    32: pokemon(name='Nidoran♂', type1='Poison'),
    33: pokemon(name='Nidorino', type1='Poison'),
    34: pokemon(name='Nidoking', type1='Poison', type2='Ground'),
    35: pokemon(name='Clefairy', type1='Fairy'),
    36: pokemon(name='Clefable', type1='Fairy'),
    37: pokemon(name='Vulpix', type1='Fire'),
    38: pokemon(name='Ninetales', type1='Fire'),
    39: pokemon(name='Jigglypuff', type1='Normal', type2='Fairy'),
    40: pokemon(name='Wigglytuff', type1='Normal', type2='Fairy'),
    41: pokemon(name='Zubat', type1='Poison', type2='Flying'),
    42: pokemon(name='Golbat', type1='Poison', type2='Flying'),
    43: pokemon(name='Oddish', type1='Grass', type2='Poison'),
    44: pokemon(name='Gloom', type1='Grass', type2='Poison'),
    45: pokemon(name='Vileplume', type1='Grass', type2='Poison'),
    46: pokemon(name='Paras', type1='Bug', type2='Grass'),
    47: pokemon(name='Parasect', type1='Bug', type2='Grass'),
    48: pokemon(name='Venonat', type1='Bug', type2='Poison'),
    49: pokemon(name='Venomoth', type1='Bug', type2='Poison'),
    50: pokemon(name='Diglett', type1='Ground'),
    51: pokemon(name='Dugtrio', type1='Ground'),
    52: pokemon(name='Meowth', type1='Normal'),
    53: pokemon(name='Persian', type1='Normal'),
    54: pokemon(name='Psyduck', type1='Water'),
    55: pokemon(name='Golduck', type1='Water'),
    56: pokemon(name='Mankey', type1='Fighting'),
    57: pokemon(name='Primeape', type1='Fighting'),
    58: pokemon(name='Growlithe', type1='Fire'),
    59: pokemon(name='Arcanine', type1='Fire'),
    60: pokemon(name='Poliwag', type1='Water'),
    61: pokemon(name='Poliwhirl', type1='Water'),
    62: pokemon(name='Poliwrath', type1='Water', type2='Fighting'),
    63: pokemon(name='Abra', type1='Psychic'),
    64: pokemon(name='Kadabra', type1='Psychic'),
    65: pokemon(name='Alakazam', type1='Psychic'),
    66: pokemon(name='Machop', type1='Fighting'),
    67: pokemon(name='Machoke', type1='Fighting'),
    68: pokemon(name='Machamp', type1='Fighting'),
    69: pokemon(name='Bellsprout', type1='Grass', type2='Poison'),
    70: pokemon(name='Weepinbell', type1='Grass', type2='Poison'),
    71: pokemon(name='Victreebel', type1='Grass', type2='Poison'),
    72: pokemon(name='Tentacool', type1='Water', type2='Poison'),
    73: pokemon(name='Tentacruel', type1='Water', type2='Poison'),
    74: pokemon(name='Geodude', type1='Rock', type2='Ground'),
    75: pokemon(name='Graveler', type1='Rock', type2='Ground'),
    76: pokemon(name='Golem', type1='Rock', type2='Ground'),
    77: pokemon(name='Ponyta', type1='Fire'),
    78: pokemon(name='Rapidash', type1='Fire'),
    79: pokemon(name='Slowpoke', type1='Water', type2='Psychic'),
    80: pokemon(name='Slowbro', type1='Water', type2='Psychic'),
    81: pokemon(name='Magnemite', type1='Electric', type2='Steel'),
    82: pokemon(name='Magneton', type1='Electric', type2='Steel'),
    83: pokemon(name='Farfetch\'d', type1='Normal', type2='Flying'),
    84: pokemon(name='Doduo', type1='Normal', type2='Flying'),
    85: pokemon(name='Dodrio', type1='Normal', type2='Flying'),
    86: pokemon(name='Seel', type1='Water'),
    87: pokemon(name='Dewgong', type1='Water', type2='Ice'),
    88: pokemon(name='Grimer', type1='Poison'),
    89: pokemon(name='Muk', type1='Poison'),
    90: pokemon(name='Shellder', type1='Water'),
    91: pokemon(name='Cloyster', type1='Water', type2='Ice'),
    92: pokemon(name='Gastly', type1='Ghost', type2='Poison'),
    93: pokemon(name='Haunter', type1='Ghost', type2='Poison'),
    94: pokemon(name='Gengar', type1='Ghost', type2='Poison'),
    95: pokemon(name='Onix', type1='Rock', type2='Ground'),
    96: pokemon(name='Drowzee', type1='Psychic'),
    97: pokemon(name='Hypno', type1='Psychic'),
    98: pokemon(name='Krabby', type1='Water'),
    99: pokemon(name='Kingler', type1='Water'),
    100: pokemon(name='Voltorb', type1='Electric'),
    101: pokemon(name='Electrode', type1='Electric'),
    102: pokemon(name='Exeggcute', type1='Grass', type2='Psychic'),
    103: pokemon(name='Exeggutor', type1='Grass', type2='Psychic'),
    104: pokemon(name='Cubone', type1='Ground'),
    105: pokemon(name='Marowak', type1='Ground'),
    106: pokemon(name='Hitmonlee', type1='Fighting'),
    107: pokemon(name='Hitmonchan', type1='Fighting'),
    108: pokemon(name='Lickitung', type1='Normal'),
    109: pokemon(name='Koffing', type1='Poison'),
    110: pokemon(name='Weezing', type1='Poison'),
    111: pokemon(name='Rhyhorn', type1='Ground', type2='Rock'),
    112: pokemon(name='Rhydon', type1='Ground', type2='Rock'),
    113: pokemon(name='Chansey', type1='Normal'),
    114: pokemon(name='Tangela', type1='Grass'),
    115: pokemon(name='Kangaskhan', type1='Normal'),
    116: pokemon(name='Horsea', type1='Water'),
    117: pokemon(name='Seadra', type1='Water'),
    118: pokemon(name='Goldeen', type1='Water'),
    119: pokemon(name='Seaking', type1='Water'),
    120: pokemon(name='Staryu', type1='Water'),
    121: pokemon(name='Starmie', type1='Water', type2='Psychic'),
    122: pokemon(name='Mr. Mime', type1='Psychic', type2='Fairy'),
    123: pokemon(name='Scyther', type1='Bug', type2='Flying'),
    124: pokemon(name='Jynx', type1='Ice', type2='Psychic'),
    125: pokemon(name='Electabuzz', type1='Electric'),
    126: pokemon(name='Magmar', type1='Fire'),
    127: pokemon(name='Pinsir', type1='Bug'),
    128: pokemon(name='Tauros', type1='Normal'),
    129: pokemon(name='Magikarp', type1='Water'),
    130: pokemon(name='Gyarados', type1='Water', type2='Flying'),
    131: pokemon(name='Lapras', type1='Water', type2='Ice'),
    132: pokemon(name='Ditto', type1='Normal'),
    133: pokemon(name='Eevee', type1='Normal'),
    134: pokemon(name='Vaporeon', type1='Water'),
    135: pokemon(name='Jolteon', type1='Electric'),
    136: pokemon(name='Flareon', type1='Fire'),
    137: pokemon(name='Porygon', type1='Normal'),
    138: pokemon(name='Omanyte', type1='Rock', type2='Water'),
    139: pokemon(name='Omastar', type1='Rock', type2='Water'),
    140: pokemon(name='Kabuto', type1='Rock', type2='Water'),
    141: pokemon(name='Kabutops', type1='Rock', type2='Water'),
    142: pokemon(name='Aerodactyl', type1='Rock', type2='Flying'),
    143: pokemon(name='Snorlax', type1='Normal'),
    144: pokemon(name='Articuno', type1='Ice', type2='Flying'),
    145: pokemon(name='Zapdos', type1='Electric', type2='Flying'),
    146: pokemon(name='Moltres', type1='Fire', type2='Flying'),
    147: pokemon(name='Dratini', type1='Dragon'),
    148: pokemon(name='Dragonair', type1='Dragon'),
    149: pokemon(name='Dragonite', type1='Dragon', type2='Flying'),
    150: pokemon(name='Mewtwo', type1='Psychic'),
    151: pokemon(name='Mew', type1='Psychic'),
    152: pokemon(name='Chikorita', type1='Grass'),
    153: pokemon(name='Bayleef', type1='Grass'),
    154: pokemon(name='Meganium', type1='Grass'),
    155: pokemon(name='Cyndaquil', type1='Fire'),
    156: pokemon(name='Quilava', type1='Fire'),
    157: pokemon(name='Typhlosion', type1='Fire'),
    158: pokemon(name='Totodile', type1='Water'),
    159: pokemon(name='Croconaw', type1='Water'),
    160: pokemon(name='Feraligatr', type1='Water'),
    161: pokemon(name='Sentret', type1='Normal'),
    162: pokemon(name='Furret', type1='Normal'),
    163: pokemon(name='Hoothoot', type1='Normal', type2='Flying'),
    164: pokemon(name='Noctowl', type1='Normal', type2='Flying'),
    165: pokemon(name='Ledyba', type1='Bug', type2='Flying'),
    166: pokemon(name='Ledian', type1='Bug', type2='Flying'),
    167: pokemon(name='Spinarak', type1='Bug', type2='Poison'),
    168: pokemon(name='Ariados', type1='Bug', type2='Poison'),
    169: pokemon(name='Crobat', type1='Poison', type2='Flying'),
    170: pokemon(name='Chinchou', type1='Water', type2='Electric'),
    171: pokemon(name='Lanturn', type1='Water', type2='Electric'),
    172: pokemon(name='Pichu', type1='Electric'),
    173: pokemon(name='Cleffa', type1='Fairy'),
    174: pokemon(name='Igglybuff', type1='Normal', type2='Fairy'),
    175: pokemon(name='Togepi', type1='Fairy'),
    176: pokemon(name='Togetic', type1='Fairy', type2='Flying'),
    177: pokemon(name='Natu', type1='Psychic', type2='Flying'),
    178: pokemon(name='Xatu', type1='Psychic', type2='Flying'),
    179: pokemon(name='Mareep', type1='Electric'),
    180: pokemon(name='Flaaffy', type1='Electric'),
    181: pokemon(name='Ampharos', type1='Electric'),
    182: pokemon(name='Bellossom', type1='Grass'),
    183: pokemon(name='Marill', type1='Water', type2='Fairy'),
    184: pokemon(name='Azumarill', type1='Water', type2='Fairy'),
    185: pokemon(name='Sudowoodo', type1='Rock'),
    186: pokemon(name='Politoed', type1='Water'),
    187: pokemon(name='Hoppip', type1='Grass', type2='Flying'),
    188: pokemon(name='Skiploom', type1='Grass', type2='Flying'),
    189: pokemon(name='Jumpluff', type1='Grass', type2='Flying'),
    190: pokemon(name='Aipom', type1='Normal'),
    191: pokemon(name='Sunkern', type1='Grass'),
    192: pokemon(name='Sunflora', type1='Grass'),
    193: pokemon(name='Yanma', type1='Bug', type2='Flying'),
    194: pokemon(name='Wooper', type1='Water', type2='Ground'),
    195: pokemon(name='Quagsire', type1='Water', type2='Ground'),
    196: pokemon(name='Espeon', type1='Psychic'),
    197: pokemon(name='Umbreon', type1='Dark'),
    198: pokemon(name='Murkrow', type1='Dark', type2='Flying'),
    199: pokemon(name='Slowking', type1='Water', type2='Psychic'),
    200: pokemon(name='Misdreavus', type1='Ghost'),
    201: pokemon(name='Unown', type1='Psychic'),
    202: pokemon(name='Wobbuffet', type1='Psychic'),
    203: pokemon(name='Girafarig', type1='Normal', type2='Psychic'),
    204: pokemon(name='Pineco', type1='Bug'),
    205: pokemon(name='Forretress', type1='Bug', type2='Steel'),
    206: pokemon(name='Dunsparce', type1='Normal'),
    207: pokemon(name='Gligar', type1='Ground', type2='Flying'),
    208: pokemon(name='Steelix', type1='Steel', type2='Ground'),
    209: pokemon(name='Snubbull', type1='Fairy'),
    210: pokemon(name='Granbull', type1='Fairy'),
    211: pokemon(name='Qwilfish', type1='Water', type2='Poison'),
    212: pokemon(name='Scizor', type1='Bug', type2='Steel'),
    213: pokemon(name='Shuckle', type1='Bug', type2='Rock'),
    214: pokemon(name='Heracross', type1='Bug', type2='Fighting'),
    215: pokemon(name='Sneasel', type1='Dark', type2='Ice'),
    216: pokemon(name='Teddiursa', type1='Normal'),
    217: pokemon(name='Ursaring', type1='Normal'),
    218: pokemon(name='Slugma', type1='Fire'),
    219: pokemon(name='Magcargo', type1='Fire', type2='Rock'),
    220: pokemon(name='Swinub', type1='Ice', type2='Ground'),
    221: pokemon(name='Piloswine', type1='Ice', type2='Ground'),
    222: pokemon(name='Corsola', type1='Water', type2='Rock'),
    223: pokemon(name='Remoraid', type1='Water'),
    224: pokemon(name='Octillery', type1='Water'),
    225: pokemon(name='Delibird', type1='Ice', type2='Flying'),
    226: pokemon(name='Mantine', type1='Water', type2='Flying'),
    227: pokemon(name='Skarmory', type1='Steel', type2='Flying'),
    228: pokemon(name='Houndour', type1='Dark', type2='Fire'),
    229: pokemon(name='Houndoom', type1='Dark', type2='Fire'),
    230: pokemon(name='Kingdra', type1='Water', type2='Dragon'),
    231: pokemon(name='Phanpy', type1='Ground'),
    232: pokemon(name='Donphan', type1='Ground'),
    233: pokemon(name='Porygon2', type1='Normal'),
    234: pokemon(name='Stantler', type1='Normal'),
    235: pokemon(name='Smeargle', type1='Normal'),
    236: pokemon(name='Tyrogue', type1='Fighting'),
    237: pokemon(name='Hitmontop', type1='Fighting'),
    238: pokemon(name='Smoochum', type1='Ice', type2='Psychic'),
    239: pokemon(name='Elekid', type1='Electric'),
    240: pokemon(name='Magby', type1='Fire'),
    241: pokemon(name='Miltank', type1='Normal'),
    242: pokemon(name='Blissey', type1='Normal'),
    243: pokemon(name='Raikou', type1='Electric'),
    244: pokemon(name='Entei', type1='Fire'),
    245: pokemon(name='Suicune', type1='Water'),
    246: pokemon(name='Larvitar', type1='Rock', type2='Ground'),
    247: pokemon(name='Pupitar', type1='Rock', type2='Ground'),
    248: pokemon(name='Tyranitar', type1='Rock', type2='Dark'),
    249: pokemon(name='Lugia', type1='Psychic', type2='Flying'),
    250: pokemon(name='Ho-oh', type1='Fire', type2='Flying'),
    251: pokemon(name='Celebi', type1='Psychic', type2='Grass'),
    252: pokemon(name='Treecko', type1='Grass'),
    253: pokemon(name='Grovyle', type1='Grass'),
    254: pokemon(name='Sceptile', type1='Grass'),
    255: pokemon(name='Torchic', type1='Fire'),
    256: pokemon(name='Combusken', type1='Fire', type2='Fighting'),
    257: pokemon(name='Blaziken', type1='Fire', type2='Fighting'),
    258: pokemon(name='Mudkip', type1='Water'),
    259: pokemon(name='Marshtomp', type1='Water', type2='Ground'),
    260: pokemon(name='Swampert', type1='Water', type2='Ground'),
    261: pokemon(name='Poochyena', type1='Dark'),
    262: pokemon(name='Mightyena', type1='Dark'),
    263: pokemon(name='Zigzagoon', type1='Normal'),
    264: pokemon(name='Linoone', type1='Normal'),
    265: pokemon(name='Wurmple', type1='Bug'),
    266: pokemon(name='Silcoon', type1='Bug'),
    267: pokemon(name='Beautifly', type1='Bug', type2='Flying'),
    268: pokemon(name='Cascoon', type1='Bug'),
    269: pokemon(name='Dustox', type1='Bug', type2='Poison'),
    270: pokemon(name='Lotad', type1='Water', type2='Grass'),
    271: pokemon(name='Lombre', type1='Water', type2='Grass'),
    272: pokemon(name='Ludicolo', type1='Water', type2='Grass'),
    273: pokemon(name='Seedot', type1='Grass'),
    274: pokemon(name='Nuzleaf', type1='Grass', type2='Dark'),
    275: pokemon(name='Shiftry', type1='Grass', type2='Dark'),
    276: pokemon(name='Taillow', type1='Normal', type2='Flying'),
    277: pokemon(name='Swellow', type1='Normal', type2='Flying'),
    278: pokemon(name='Wingull', type1='Water', type2='Flying'),
    279: pokemon(name='Pelipper', type1='Water', type2='Flying'),
    280: pokemon(name='Ralts', type1='Psychic', type2='Fairy'),
    281: pokemon(name='Kirlia', type1='Psychic', type2='Fairy'),
    282: pokemon(name='Gardevoir', type1='Psychic', type2='Fairy'),
    283: pokemon(name='Surskit', type1='Bug', type2='Water'),
    284: pokemon(name='Masquerain', type1='Bug', type2='Flying'),
    285: pokemon(name='Shroomish', type1='Grass'),
    286: pokemon(name='Breloom', type1='Grass', type2='Fighting'),
    287: pokemon(name='Slakoth', type1='Normal'),
    288: pokemon(name='Vigoroth', type1='Normal'),
    289: pokemon(name='Slaking', type1='Normal'),
    290: pokemon(name='Nincada', type1='Bug', type2='Ground'),
    291: pokemon(name='Ninjask', type1='Bug', type2='Flying'),
    292: pokemon(name='Shedinja', type1='Bug', type2='Ghost'),
    293: pokemon(name='Whismur', type1='Normal'),
    294: pokemon(name='Loudred', type1='Normal'),
    295: pokemon(name='Exploud', type1='Normal'),
    296: pokemon(name='Makuhita', type1='Fighting'),
    297: pokemon(name='Hariyama', type1='Fighting'),
    298: pokemon(name='Azurill', type1='Normal', type2='Fairy'),
    299: pokemon(name='Nosepass', type1='Rock'),
    300: pokemon(name='Skitty', type1='Normal'),
    301: pokemon(name='Delcatty', type1='Normal'),
    302: pokemon(name='Sableye', type1='Dark', type2='Ghost'),
    303: pokemon(name='Mawile', type1='Steel', type2='Fairy'),
    304: pokemon(name='Aron', type1='Steel', type2='Rock'),
    305: pokemon(name='Lairon', type1='Steel', type2='Rock'),
    306: pokemon(name='Aggron', type1='Steel', type2='Rock'),
    307: pokemon(name='Meditite', type1='Fighting', type2='Psychic'),
    308: pokemon(name='Medicham', type1='Fighting', type2='Psychic'),
    309: pokemon(name='Electrike', type1='Electric'),
    310: pokemon(name='Manectric', type1='Electric'),
    311: pokemon(name='Plusle', type1='Electric'),
    312: pokemon(name='Minun', type1='Electric'),
    313: pokemon(name='Volbeat', type1='Bug'),
    314: pokemon(name='Illumise', type1='Bug'),
    315: pokemon(name='Roselia', type1='Grass', type2='Poison'),
    316: pokemon(name='Gulpin', type1='Poison'),
    317: pokemon(name='Swalot', type1='Poison'),
    318: pokemon(name='Carvanha', type1='Water', type2='Dark'),
    319: pokemon(name='Sharpedo', type1='Water', type2='Dark'),
    320: pokemon(name='Wailmer', type1='Water'),
    321: pokemon(name='Wailord', type1='Water'),
    322: pokemon(name='Numel', type1='Fire', type2='Ground'),
    323: pokemon(name='Camerupt', type1='Fire', type2='Ground'),
    324: pokemon(name='Torkoal', type1='Fire'),
    325: pokemon(name='Spoink', type1='Psychic'),
    326: pokemon(name='Grumpig', type1='Psychic'),
    327: pokemon(name='Spinda', type1='Normal'),
    328: pokemon(name='Trapinch', type1='Ground'),
    329: pokemon(name='Vibrava', type1='Ground', type2='Dragon'),
    330: pokemon(name='Flygon', type1='Ground', type2='Dragon'),
    331: pokemon(name='Cacnea', type1='Grass'),
    332: pokemon(name='Cacturne', type1='Grass', type2='Dark'),
    333: pokemon(name='Swablu', type1='Normal', type2='Flying'),
    334: pokemon(name='Altaria', type1='Dragon', type2='Flying'),
    335: pokemon(name='Zangoose', type1='Normal'),
    336: pokemon(name='Seviper', type1='Poison'),
    337: pokemon(name='Lunatone', type1='Rock', type2='Psychic'),
    338: pokemon(name='Solrock', type1='Rock', type2='Psychic'),
    339: pokemon(name='Barboach', type1='Water', type2='Ground'),
    340: pokemon(name='Whiscash', type1='Water', type2='Ground'),
    341: pokemon(name='Corphish', type1='Water'),
    342: pokemon(name='Crawdaunt', type1='Water', type2='Dark'),
    343: pokemon(name='Baltoy', type1='Ground', type2='Psychic'),
    344: pokemon(name='Claydol', type1='Ground', type2='Psychic'),
    345: pokemon(name='Lileep', type1='Rock', type2='Grass'),
    346: pokemon(name='Cradily', type1='Rock', type2='Grass'),
    347: pokemon(name='Anorith', type1='Rock', type2='Bug'),
    348: pokemon(name='Armaldo', type1='Rock', type2='Bug'),
    349: pokemon(name='Feebas', type1='Water'),
    350: pokemon(name='Milotic', type1='Water'),
    351: pokemon(name='Castform', type1='Normal'),
    352: pokemon(name='Kecleon', type1='Normal'),
    353: pokemon(name='Shuppet', type1='Ghost'),
    354: pokemon(name='Banette', type1='Ghost'),
    355: pokemon(name='Duskull', type1='Ghost'),
    356: pokemon(name='Dusclops', type1='Ghost'),
    357: pokemon(name='Tropius', type1='Grass', type2='Flying'),
    358: pokemon(name='Chimecho', type1='Psychic'),
    359: pokemon(name='Absol', type1='Dark'),
    360: pokemon(name='Wynaut', type1='Psychic'),
    361: pokemon(name='Snorunt', type1='Ice'),
    362: pokemon(name='Glalie', type1='Ice'),
    363: pokemon(name='Spheal', type1='Ice', type2='Water'),
    364: pokemon(name='Sealeo', type1='Ice', type2='Water'),
    365: pokemon(name='Walrein', type1='Ice', type2='Water'),
    366: pokemon(name='Clamperl', type1='Water'),
    367: pokemon(name='Huntail', type1='Water'),
    368: pokemon(name='Gorebyss', type1='Water'),
    369: pokemon(name='Relicanth', type1='Water', type2='Rock'),
    370: pokemon(name='Luvdisc', type1='Water'),
    371: pokemon(name='Bagon', type1='Dragon'),
    372: pokemon(name='Shelgon', type1='Dragon'),
    373: pokemon(name='Salamence', type1='Dragon', type2='Flying'),
    374: pokemon(name='Beldum', type1='Steel', type2='Psychic'),
    375: pokemon(name='Metang', type1='Steel', type2='Psychic'),
    376: pokemon(name='Metagross', type1='Steel', type2='Psychic'),
    377: pokemon(name='Regirock', type1='Rock'),
    378: pokemon(name='Regice', type1='Ice'),
    379: pokemon(name='Registeel', type1='Steel'),
    380: pokemon(name='Latias', type1='Dragon', type2='Psychic'),
    381: pokemon(name='Latios', type1='Dragon', type2='Psychic'),
    382: pokemon(name='Kyogre', type1='Water'),
    383: pokemon(name='Groudon', type1='Ground'),
    384: pokemon(name='Rayquaza', type1='Dragon', type2='Flying'),
    385: pokemon(name='Jirachi', type1='Steel', type2='Psychic'),
    386: pokemon(name='Deoxys (N)', type1='Psychic'),
    387: pokemon(name='Turtwig', type1='Grass'),
    388: pokemon(name='Grotle', type1='Grass'),
    389: pokemon(name='Torterra', type1='Grass', type2='Ground'),
    390: pokemon(name='Chimchar', type1='Fire'),
    391: pokemon(name='Monferno', type1='Fire', type2='Fighting'),
    392: pokemon(name='Infernape', type1='Fire', type2='Fighting'),
    393: pokemon(name='Piplup', type1='Water'),
    394: pokemon(name='Prinplup', type1='Water'),
    395: pokemon(name='Empoleon', type1='Water', type2='Steel'),
    396: pokemon(name='Starly', type1='Normal', type2='Flying'),
    397: pokemon(name='Staravia', type1='Normal', type2='Flying'),
    398: pokemon(name='Staraptor', type1='Normal', type2='Flying'),
    399: pokemon(name='Bidoof', type1='Normal'),
    400: pokemon(name='Bibarel', type1='Normal', type2='Water'),
    401: pokemon(name='Kricketot', type1='Bug'),
    402: pokemon(name='Kricketune', type1='Bug'),
    403: pokemon(name='Shinx', type1='Electric'),
    404: pokemon(name='Luxio', type1='Electric'),
    405: pokemon(name='Luxray', type1='Electric'),
    406: pokemon(name='Budew', type1='Grass', type2='Poison'),
    407: pokemon(name='Roserade', type1='Grass', type2='Poison'),
    408: pokemon(name='Cranidos', type1='Rock'),
    409: pokemon(name='Rampardos', type1='Rock'),
    410: pokemon(name='Shieldon', type1='Rock', type2='Steel'),
    411: pokemon(name='Bastiodon', type1='Rock', type2='Steel'),
    412: pokemon(name='Burmy', type1='Bug'),
    413: pokemon(name='Wormadam (P)', type1='Bug', type2='Grass'),
    414: pokemon(name='Mothim', type1='Bug', type2='Flying'),
    415: pokemon(name='Combee', type1='Bug', type2='Flying'),
    416: pokemon(name='Vespiquen', type1='Bug', type2='Flying'),
    417: pokemon(name='Pachirisu', type1='Electric'),
    418: pokemon(name='Buizel', type1='Water'),
    419: pokemon(name='Floatzel', type1='Water'),
    420: pokemon(name='Cherubi', type1='Grass'),
    421: pokemon(name='Cherrim', type1='Grass'),
    422: pokemon(name='Shellos', type1='Water'),
    423: pokemon(name='Gastrodon', type1='Water', type2='Ground'),
    424: pokemon(name='Ambipom', type1='Normal'),
    425: pokemon(name='Drifloon', type1='Ghost', type2='Flying'),
    426: pokemon(name='Drifblim', type1='Ghost', type2='Flying'),
    427: pokemon(name='Buneary', type1='Normal'),
    428: pokemon(name='Lopunny', type1='Normal'),
    429: pokemon(name='Mismagius', type1='Ghost'),
    430: pokemon(name='Honchkrow', type1='Dark', type2='Flying'),
    431: pokemon(name='Glameow', type1='Normal'),
    432: pokemon(name='Purugly', type1='Normal'),
    433: pokemon(name='Chingling', type1='Psychic'),
    434: pokemon(name='Stunky', type1='Poison', type2='Dark'),
    435: pokemon(name='Skuntank', type1='Poison', type2='Dark'),
    436: pokemon(name='Bronzor', type1='Steel', type2='Psychic'),
    437: pokemon(name='Bronzong', type1='Steel', type2='Psychic'),
    438: pokemon(name='Bonsly', type1='Rock'),
    439: pokemon(name='Mime Jr.', type1='Psychic', type2='Fairy'),
    440: pokemon(name='Happiny', type1='Normal'),
    441: pokemon(name='Chatot', type1='Normal', type2='Flying'),
    442: pokemon(name='Spiritomb', type1='Ghost', type2='Dark'),
    443: pokemon(name='Gible', type1='Dragon', type2='Ground'),
    444: pokemon(name='Gabite', type1='Dragon', type2='Ground'),
    445: pokemon(name='Garchomp', type1='Dragon', type2='Ground'),
    446: pokemon(name='Munchlax', type1='Normal'),
    447: pokemon(name='Riolu', type1='Fighting'),
    448: pokemon(name='Lucario', type1='Fighting', type2='Steel'),
    449: pokemon(name='Hippopotas', type1='Ground'),
    450: pokemon(name='Hippowdon', type1='Ground'),
    451: pokemon(name='Skorupi', type1='Poison', type2='Bug'),
    452: pokemon(name='Drapion', type1='Poison', type2='Dark'),
    453: pokemon(name='Croagunk', type1='Poison', type2='Fighting'),
    454: pokemon(name='Toxicroak', type1='Poison', type2='Fighting'),
    455: pokemon(name='Carnivine', type1='Grass'),
    456: pokemon(name='Finneon', type1='Water'),
    457: pokemon(name='Lumineon', type1='Water'),
    458: pokemon(name='Mantyke', type1='Water', type2='Flying'),
    459: pokemon(name='Snover', type1='Ice', type2='Grass'),
    460: pokemon(name='Abomasnow', type1='Ice', type2='Grass'),
    461: pokemon(name='Weavile', type1='Dark', type2='Ice'),
    462: pokemon(name='Magnezone', type1='Electric', type2='Steel'),
    463: pokemon(name='Lickilicky', type1='Normal'),
    464: pokemon(name='Rhyperior', type1='Ground', type2='Rock'),
    465: pokemon(name='Tangrowth', type1='Grass'),
    466: pokemon(name='Electivire', type1='Electric'),
    467: pokemon(name='Magmortar', type1='Fire'),
    468: pokemon(name='Togekiss', type1='Fairy', type2='Flying'),
    469: pokemon(name='Yanmega', type1='Bug', type2='Flying'),
    470: pokemon(name='Leafeon', type1='Grass'),
    471: pokemon(name='Glaceon', type1='Ice'),
    472: pokemon(name='Gliscor', type1='Ground', type2='Flying'),
    473: pokemon(name='Mamoswine', type1='Ice', type2='Ground'),
    474: pokemon(name='Porygon-Z', type1='Normal'),
    475: pokemon(name='Gallade', type1='Psychic', type2='Fighting'),
    476: pokemon(name='Probopass', type1='Rock', type2='Steel'),
    477: pokemon(name='Dusknoir', type1='Ghost'),
    478: pokemon(name='Froslass', type1='Ice', type2='Ghost'),
    479: pokemon(name='Rotom', type1='Electric', type2='Ghost'),
    480: pokemon(name='Uxie', type1='Psychic'),
    481: pokemon(name='Mesprit', type1='Psychic'),
    482: pokemon(name='Azelf', type1='Psychic'),
    483: pokemon(name='Dialga', type1='Steel', type2='Dragon'),
    484: pokemon(name='Palkia', type1='Water', type2='Dragon'),
    485: pokemon(name='Heatran', type1='Fire', type2='Steel'),
    486: pokemon(name='Regigigas', type1='Normal'),
    487: pokemon(name='Giratina', type1='Ghost', type2='Dragon'),
    488: pokemon(name='Cresselia', type1='Psychic'),
    489: pokemon(name='Phione', type1='Water'),
    490: pokemon(name='Manaphy', type1='Water'),
    491: pokemon(name='Darkrai', type1='Dark'),
    492: pokemon(name='Shaymin', type1='Grass'),
    493: pokemon(name='Arceus', type1='Normal'),
    808: pokemon(name='Meltan', type1='Steel'),
    809: pokemon(name='Melmetal', type1='Steel')
})
